### ISSUE TITLE
nomenclature for 'over'

### ISSUE THREAD

**Issue by Amsoht** [MrFuppes/IDL_IAU_Chrom#2]
I am currently working on implementing a new integration method. I wonder, how are the different values for 'over', e.g. '1', '123', '123467' created?
Cheers, Thomas
https://github.com/MrFuppes/IDL_IAU_Chrom/blob/7a115eed2d6b1c3323f76037d5833a1a942e66b1/Plot/plot_routine_pobj1.pro#L78

**Comment by FObersteiner** [comment]
the number `over`refers to the graphs that are plotted. e.g. 134 will plot to graphs 1, 3, 4 and set the others to [0,0]. (!) it's not zero-based, so 1 means `p_obj1[0]` - that is because `0` is used to refresh ALL graphs. Hope that clarifies a bit... seems like a weird way to do such a thing in retrospect ;-)

**Comment by Amsoht** [comment]
This helps, thank you :)
